name = "ESP32-C6-DevKitM-1"
manufacturer = "Espressif"
is_main_board = true
standard = "ESP32"
cpu = "Microchip AVR"
ram = 2
flash = 32
required_crates = ["ufmt", "nb", "embedded-hal", "embedded-time", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[pinout]
interfaces = [
	{ name = "GPIO", alias_fmt = "GPIO{}"},
	{ name = "I2C", bus = true, roles = [{name = "SDA"}, {name = "SCL"}] },
	{ name = "SPI", bus = true, roles = [{name = "SCK"}, {name = "MISO"}, {name = "MOSI"}, {name = "SS"}] },
	{ name = "UART", bus = true, roles = [{name = "TX"}, {name = "RX"}] },
	{ name = "USB", bus = true, roles = [{name = "USB_D+"}, {name = "USB_D-"}] },
]
pins = [
	# power & control
	{ physical = 0, silkscreen = "3V3" },
	{ physical = 1, silkscreen = "RST" },

	# gpio
	{ physical = 2, silkscreen = "2", roles = [
		{ name = "GPIO", id = 2 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 3, silkscreen = "3", roles = [
		{ name = "GPIO", id = 3 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 4, silkscreen = "4", roles = [
		{ name = "GPIO", id = 4 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 5, silkscreen = "5", roles = [
		{ name = "GPIO", id = 5 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 6, silkscreen = "0/N", roles = [
		{ name = "GPIO", id = 0 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 7, silkscreen = "1/N", roles = [
		{ name = "GPIO", id = 1 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 8, silkscreen = "8", roles = [
		{ name = "GPIO", id = 8 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 9, silkscreen = "6", roles = [
		{ name = "GPIO", id = 6 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 10, silkscreen = "7", roles = [
		{ name = "GPIO", id = 7 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 11, silkscreen = "14", roles = [
		{ name = "GPIO", id = 14 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},

	# power
	{ physical = 12, silkscreen = "G" },
	{ physical = 13, silkscreen = "5V" },
	{ physical = 14, silkscreen = "G" },
	{ physical = 15, silkscreen = "G" },

	# default uart
	{ physical = 16, silkscreen = "TX", roles = [
		{ name = "TX" },
	]},
	{ physical = 17, silkscreen = "RX", roles = [
		{ name = "RX" },
	]},

	# gpio
	{ physical = 18, silkscreen = "23", roles = [
		{ name = "GPIO", id = 23 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 19, silkscreen = "22", roles = [
		{ name = "GPIO", id = 22 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 20, silkscreen = "21", roles = [
		{ name = "GPIO", id = 21 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 21, silkscreen = "20", roles = [
		{ name = "GPIO", id = 20 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 22, silkscreen = "19", roles = [
		{ name = "GPIO", id = 19 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 23, silkscreen = "18", roles = [
		{ name = "GPIO", id = 18 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 24, silkscreen = "15", roles = [
		{ name = "GPIO", id = 15 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},
	{ physical = 25, silkscreen = "9", roles = [
		{ name = "GPIO", id = 9 },
		{ name = "I2C" },
		{ name = "SPI" },
	]},

	# power & usb
	{ physical = 26, silkscreen = "G" },
	{ physical = 27, silkscreen = "13", roles = [
		{ name = "USB_D+" },
	]},
	{ physical = 28, silkscreen = "12", roles = [
		{ name = "USB_D-" },
	]},
	{ physical = 29, silkscreen = "G" },
]
