name = "Push Button"
board_type = "Peripheral"

related_crates = ["embedded-hal"]

[pinout]
interfaces = [
	{ name = "SPI", bus = true, roles = [{name = "SCK"}, {name = "MISO"}, {name = "MOSI"}, {name = "SS"}] },
]
pins = [
	{ physical = 0, silkscreen = "MISO", roles = [
		{ name = "MISO" },
	]},
]

# [pinout]
# interfaces = [
# 	{ name = "GPIO" },
# ]
# pins = [
# 	{ physical = 0, silkscreen = "Input", roles = [
# 		{ name = "GPIO", direction = "Input" },
# 	]},
# ]