[build]
rustflags = [
    "-C",
    "target-cpu=atmega328p",
]
target = "avr-none"

[target.'cfg(target_arch = "avr")']
linker = "/home/jon/Assignments/FALL_2025/CEN3908/iron-coder-25-26/Redist/Arduino/toolchain/linux-x86_64/bin/avr-gcc"
runner = "ravedude"

[unstable]
build-std = ["core"]
