name = "LED"
board_type = "Peripheral"

related_crates = ["embedded-hal"]

# [pinout]
# interfaces = [
# 	{ name = "I2C", bus = true, roles = [{name = "SDA"}, {name = "SCL"}] },
# ]
# pins = [
# 	{ physical = 0, silkscreen = "SDA", roles = [
# 		{ name = "SDA" },
# 	]},
# ]

[pinout]
interfaces = [
	{ name = "GPIO" },
]
pins = [
	{ physical = 0, silkscreen = "Anode", roles = [
		{ name = "GPIO", direction = "Output" },
	]},
]