panel_fill = "#4f78dbff"
window_stroke_color = "#586e75ff"
extreme_bg_color = "#575757ff"
window_fill = "#252525ff"
code_bg_color = "#ffffffff"
warn_fg_color = "#839496ff"
error_fg_color = "#839496ff"
faint_bg_color = "#c17c33ff"
hyperlink_color = "#839496ff"
