panel_fill = "#b2a984ff"
error_fg_color = "#839496ff"
code_bg_color = "#000000ff"
window_fill = "#f4ebc3ff"
hyperlink_color = "#839496ff"
extreme_bg_color = "#fcaec0ff"
window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
faint_bg_color = "#ecc4b2ff"
