panel_fill = "#b2a984ff"
hyperlink_color = "#839496ff"
window_fill = "#f4ebc3ff"
extreme_bg_color = "#feb0c2ff"
faint_bg_color = "#ecc4b2ff"
window_stroke_color = "#586e75ff"
error_fg_color = "#839496ff"
warn_fg_color = "#839496ff"
code_bg_color = "#000000ff"
